### ISSUE TITLE
Palette.getColor() -> Color parameter outside of expected range

### ISSUE THREAD

**Issue by tmgeorge2** [MTrop/DoomStruct#18]
Hi, 1st I am new to Java and I hope I didn't screwed this up.
I actually want to use some sprites from doom.wad in libGDX as texture. Currently I read from Picture pixel by pixel and call Palette.getColor() which sometimes throws an error.

I tried to debug it but only got hold of java.awt.Color(int r, int g, int b) and for this index the r-component is -93. 

(BTW eclipse just told me: Unable to install breakpoints in net.mtrop... due to missing line number attributes. Modify compiler options to generate line number attributes")

```
public class Test {
	public static void main(String[] args) {
		try {
			WadFile wad = new WadFile("doom.wad");

			final Palette pal = wad.getDataAs("playpal", Palette.class);

			var c2 = pal.getColor(67);
		} catch (Exception e) {
			System.out.println(e);
		}
	}
}
```

**Comment by MTrop** [comment]
You're right - `getColor()` did not convert the byte components correctly.

If you can, you can get the `int` ARGB value of a palette color using `getColorARGB()`. That way, you save a step by not creating a `Color` object.

Fixed in commit 3af399b0a9714e139578d0f80afea53980770366.
